// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Test} from "forge-std/Test.sol";

import {HookFeeSplit} from "../src/HookFeeSplit.sol";
import {FeeSplitParityCases} from "./FeeSplitParityCases.sol";

/// @notice The mechanical link between the Lean model and the contract: every row of
///         `FeeSplitParityCases.sol` — generated by `verification/FeeSplit.lean`, whose proofs
///         establish the same properties over the same functions — is replayed through
///         `HookFeeSplit` and must agree field by field.
/// @dev Regenerate the fixture with `lean --run verification/FeeSplit.lean`; the model and the
///      contract are only in sync if this test is green.
contract FeeSplitParityTest is Test {
    function test_parity_replaysEveryGeneratedCase() public {
        FeeSplitParityCases.Case[] memory cs = FeeSplitParityCases.cases();
        assertEq(cs.length, FeeSplitParityCases.caseCount(), "fixture length");
        assertGt(cs.length, 400, "the fixture must cover a real cross product");

        for (uint256 i; i < cs.length; ++i) {
            FeeSplitParityCases.Case memory c = cs[i];

            (uint256 owner, uint256 lp, uint256 buyback) = HookFeeSplit.split(c.amount, c.ownerBps, c.lpBps);
            assertEq(owner, c.owner, "owner share");
            assertEq(lp, c.lp, "lp share");
            assertEq(buyback, c.buyback, "buyback share");
            assertEq(HookFeeSplit.hookFee(c.amount, c.hookFeePips), c.fee, "hook fee");
            assertEq(HookFeeSplit.slippageFloor(c.spotOut, c.slippageBps), c.floor, "slippage floor");

            // The two properties the Lean file proves, re-checked on the contract's own outputs.
            assertEq(owner + lp + buyback, c.amount, "conservation: nothing is stranded");
            assertLe(owner, c.amount * HookFeeSplit.MAX_OWNER_BPS / HookFeeSplit.BPS, "owner ceiling");
        }
    }

    /// @dev The quadrant predicate is the one the kernel's specified-leg quote take uses, and the
    ///      Lean file proves it is equivalent to "the quote is the specified currency".
    function test_quadrantPredicate() public pure {
        assertTrue(HookFeeSplit.chargeable(true, true), "exact-input buy pays");
        assertTrue(HookFeeSplit.chargeable(false, false), "exact-output sell pays");
        assertFalse(HookFeeSplit.chargeable(true, false), "exact-output buy does not");
        assertFalse(HookFeeSplit.chargeable(false, true), "exact-input sell does not");
    }
}
