// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title IHookrEngagementReceiptSink
/// @notice Optional post-swap accounting called by an authenticated router after settlement.
interface IHookrEngagementReceiptSink {
    /// @notice A completed router execution, generated by the pinned router from the swap, never from caller-supplied
    ///         volume. quoteVolume is the actual core quote magnitude before custom fees and refunds, in raw
    ///         quote units.
    struct EngagementReceipt {
        /// @notice The chain the swap ran on.
        uint256 chainId;
        /// @notice The root of the swapped pool.
        address root;
        /// @notice The swapped pool.
        bytes32 poolId;
        /// @notice The pool's policy hash.
        bytes32 configHash;
        /// @notice The pool's quote currency.
        address quoteAsset;
        /// @notice The swap's authenticated payer.
        address participant;
        /// @notice The swap's quote volume in raw quote units.
        uint256 quoteVolume;
        /// @notice The execution's unique id.
        bytes32 executionId;
        /// @notice The timestamp of the swap.
        uint64 executedAt;
        /// @notice The kind of flow; zero for a router swap.
        uint8 flowType;
    }

    /// @notice Return the only router permitted to submit completed execution receipts.
    /// @return The router.
    function trustedRouter() external view returns (address);
    /// @notice Return the PoolManager whose lock state guards receipt submission.
    /// @return The PoolManager.
    function poolManager() external view returns (address);
    /// @notice Credit explicitly selected campaigns from a completed router execution.
    /// @param receipt The completed execution.
    /// @param campaignIds The programs the execution is recorded for, at most eight.
    function recordExecution(EngagementReceipt calldata receipt, uint256[] calldata campaignIds) external;
}
